fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
      address: "soninishant287@gmail.com"
      sender_name: "Nishant Soni"
  registration:
        confirmation:
            enabled: true